apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: runner-deploy-jimmy #can change name
spec:
  replicas: 1
  template:
    spec:
      repository: newkung6/actionrunner-selfhost #Github repo url user/repo
      labels:
      - for-community-only #tag for run-on
