# This is a basic workflow to help you get started with Actions
name: Hello World

# Controls when the action will run.
on:
  push:
    tags:
    - 'v1.*.*' #triger when push tag v1.x.x
    # branches:
    # - 'main'  #Triger when push on branch

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: for-community-only #TODO change selfhost-name here
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!

    # # Runs docker hello-world
    - name: Hello from Docker
      run: docker run hello-world
