name: Docker build and test

on:
  push:
    tags:
    - 'v2.*.*'
  workflow_dispatch:
# you can trigger on anything you want

jobs:
  build:
    runs-on: for-community-only

    steps:
    - uses: actions/checkout@v2
    - name: Build Docker image
      run: docker build -t sample/dockerpython .
    - name: Run tests inside the container
      run: docker run sample/dockerpython
