name: CI-DOCKER-PUSH

on:
  push:
    tags:
    - 'v3.*.*'

jobs:
  docker:
    runs-on: for-community-only
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set output
      id: meta
      run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }} #Generate From Docker Hub
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: true
        context: sample/dockerpython #path of Dockerfile <context>/Dockerfile 
        tags: ${{ vars.DOCKERHUB_USERNAME }}/${{ vars.DOCKERHUB_REPONAME }}:${{ steps.meta.outputs.tag }} #Tag Image for push in docker HUB
